"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
import os
# URL to use when referring to static files (where Django will serve static files from)
STATIC_URL = '/static/'

# The absolute path to the directory where collectstatic will collect static files for deployment.
GRAPPELLI_ADMIN_TITLE = "Crystal Mart"

MEDIA_URL = '/media/'
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_ROOT = os.path.join(BASE_DIR, 'myproject','image')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n8=qlq289*t$0wcbxx3(@o+$^gelsq!-b=3!de=2fe%#y25hoo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True 

ALLOWED_HOSTS = ['192.168.1.9','localhost','127.0.0.1:8000']


# Application definition

INSTALLED_APPS = [
   'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp'
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

JAZZMIN_SETTINGS = {
    # Site title displayed in the browser window and on the login screen.
    "site_title": "Admin",
    
    # Header text displayed at the top left of the admin.
    "site_header": "Admin",
    
    # The brand name displayed in the admin; can be the same as your site name.
    "site_brand": "Crystal Mart",
    
    # Relative path to your logo image in your static files.
    # Place your logo image (e.g., crystalmart_logo.png) in your static directory.
    "site_logo": "img/Fevicon.jpg",
    
    # Optional CSS classes for your logo (e.g., to display it as a circle).
    # "site_logo_classes": "img-circle",
    
    # Relative path to a site icon (favicon) image.
    "site_icon": "img/Fevicon-1.png",
    
    # Welcome sign shown on the login page.
    "welcome_sign": "Crystal Mart",
    
    # Copyright text displayed in the footer.
    "copyright": "© 2025 Sirmedia",
    
    # Links to display in the top menu. You can add a link to view your public site.
    "topmenu_links": [
        {"name": "View Site", "url": "/", "new_window": False},
        {"app": "auth", "name": "Auth"},
    ],
    
    # Links in the user menu (usually at the top right).
    "usermenu_links": [
        {"name": "Support", "url": "https://support.crystalmart.com", "new_window": True},
        {"model": "auth.user"},  # Link to your user change list.
    ],
    
    # Display options for the sidebar.
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # Optionally hide entire apps or specific models from the sidebar.
    "hide_apps": [],
    "hide_models": [],
    
    # Optionally control the ordering of apps/models in the sidebar.
    "order_with_respect_to": ["auth", "myapp"],  # Adjust "myapp" to your custom apps.
    
    # Icon settings (uses FontAwesome 5 classes).
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        # Add other models and apps as needed.
    },
    
    # Default icons for apps (parents) and models (children) if not specified above.
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    
    # Activate modal windows for related fields in the admin forms.
    "related_modal_active": True,
    
    # Optionally include custom CSS or JavaScript by providing the paths to your static files.
    "custom_css": None,  # e.g., "css/custom_admin.css"
    "custom_js": None,   # e.g., "js/custom_admin.js"
    
    # UI Builder (a drag-and-drop tool to build your sidebar layout). Set to False if you don't need it.
    "show_ui_builder": False,
}

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "saadradhanpuri@gmail.com"
EMAIL_HOST_PASSWORD = "Saad#3909"