# Generated by Django 4.2.5 on 2024-03-12 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_branding'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_category',
            name='branding_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.branding'),
        ),
    ]
