# Generated by Django 4.2.5 on 2024-03-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_prize_product_prize_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='name',
            field=models.IntegerField(),
        ),
    ]
