# Generated by Django 4.2.5 on 2024-03-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_prize_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
