# Generated by Django 4.2.5 on 2024-03-29 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_product_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_c',
        ),
    ]
